---
- name: Configuring the OSPF on Router 1
  hosts: R1
  gather_facts: false
  connection: local

  vars:
    cli:
      username: cisco
      password: cisco123

  tasks:
    - name: Enable OSPF on R1
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0
        
      register: print_output
    - debug: var=print_output

- name: Configuration of OSPF on Router 2
  hosts: R2
  gather_facts: false
  connection: local

  vars:
    cli:
      username: cisco
      password: cisco123

  tasks:
    - name: Enable OSPF on R2
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0
        
      register: print_output
    - debug: var=print_output
